/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Get a snapshot of the candidate graph.
Returns nodes and links formatted for react-force-graph-2d.
 * @summary Get All Candidates Graph
 */
export const getAllCandidatesGraphApiNeo4jCandidatesGetQueryLimitDefault = 50;

export const getAllCandidatesGraphApiNeo4jCandidatesGetQueryParams = zod.object({
  "limit": zod.number().default(getAllCandidatesGraphApiNeo4jCandidatesGetQueryLimitDefault)
})

export const getAllCandidatesGraphApiNeo4jCandidatesGetResponse = zod.object({
  "nodes": zod.array(zod.object({
  "id": zod.string(),
  "label": zod.string()
}).describe('Node structure for react-force-graph.')),
  "links": zod.array(zod.object({
  "source": zod.string(),
  "target": zod.string(),
  "type": zod.string()
}).describe('Link structure for react-force-graph.'))
}).describe('Complete graph data format for frontend.')

/**
 * Get the graph for a specific candidate by username or ID.
Returns nodes and links formatted for react-force-graph-2d.
 * @summary Get Candidate Graph
 */
export const getCandidateGraphApiNeo4jCandidatesUsernameOrIdGetParams = zod.object({
  "username_or_id": zod.string()
})

export const getCandidateGraphApiNeo4jCandidatesUsernameOrIdGetResponse = zod.object({
  "nodes": zod.array(zod.object({
  "id": zod.string(),
  "label": zod.string()
}).describe('Node structure for react-force-graph.')),
  "links": zod.array(zod.object({
  "source": zod.string(),
  "target": zod.string(),
  "type": zod.string()
}).describe('Link structure for react-force-graph.'))
}).describe('Complete graph data format for frontend.')

/**
 * Delete a candidate node and its relationships.
 * @summary Delete Candidate
 */
export const deleteCandidateApiNeo4jCandidatesCandidateIdDeleteParams = zod.object({
  "candidate_id": zod.string()
})

export const deleteCandidateApiNeo4jCandidatesCandidateIdDeleteResponse = zod.unknown()

/**
 * Get graph centered around a specific entity (Skill, Location, etc.).
Returns nodes and links formatted for react-force-graph-2d.
 * @summary Get Graph By Filter
 */
export const getGraphByFilterApiNeo4jGraphFilterGetQueryParams = zod.object({
  "type": zod.string().describe('Filter type: skill, location, education, repo'),
  "value": zod.string().describe('Value to filter by (e.g., \'Python\', \'Thailand\')')
})

export const getGraphByFilterApiNeo4jGraphFilterGetResponse = zod.object({
  "nodes": zod.array(zod.object({
  "id": zod.string(),
  "label": zod.string()
}).describe('Node structure for react-force-graph.')),
  "links": zod.array(zod.object({
  "source": zod.string(),
  "target": zod.string(),
  "type": zod.string()
}).describe('Link structure for react-force-graph.'))
}).describe('Complete graph data format for frontend.')

