/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import type { CandidateAvatarUrl } from './candidate-avatar-url';
import type { CandidateBio } from './candidate-bio';
import type { CandidateLocation } from './candidate-location';
import type { CandidateAnalysisProperty } from './candidate-analysis-property';

/**
 * Full candidate schema
 */
export interface Candidate {
  username: string;
  profile_url: string;
  avatar_url?: CandidateAvatarUrl;
  bio?: CandidateBio;
  location?: CandidateLocation;
  id: string;
  job_id: string;
  created_at: string;
  analysis?: CandidateAnalysisProperty;
}
