/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import type { CandidateAnalysisTopRepositoriesItem } from './candidate-analysis-top-repositories-item';

/**
 * Candidate analysis results
 */
export interface CandidateAnalysis {
  /**
   * @minimum 0
   * @maximum 100
   */
  fit_score: number;
  skills?: string[];
  strengths?: string[];
  concerns?: string[];
  top_repositories?: CandidateAnalysisTopRepositoriesItem[];
}
