/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import type { GraphNode } from './graph-node';
import type { GraphLink } from './graph-link';

/**
 * Complete graph data format for frontend.
 */
export interface ForceGraphData {
  nodes: GraphNode[];
  links: GraphLink[];
}
