/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */

export type GetGraphByFilterApiNeo4jGraphFilterGetParams = {
/**
 * Filter type: skill, location, education, repo
 */
type: string;
/**
 * Value to filter by (e.g., 'Python', 'Thailand')
 */
value: string;
};
