/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */

/**
 * Node structure for react-force-graph.
 */
export interface GraphNode {
  id: string;
  label: string;
  [key: string]: unknown;
 }
