/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import type { JobCreateLocation } from './job-create-location';
import type { JobCreateModelProvider } from './job-create-model-provider';
import type { JobCreateRecruiterName } from './job-create-recruiter-name';
import type { JobCreateLanguageRequirement } from './job-create-language-requirement';
import type { JobCreateKeyResponsibilities } from './job-create-key-responsibilities';
import type { JobCreateCoreSkillRequirement } from './job-create-core-skill-requirement';
import type { JobCreateFamiliarWith } from './job-create-familiar-with';
import type { JobCreateWorkType } from './job-create-work-type';
import type { JobCreateYearsOfExperience } from './job-create-years-of-experience';
import type { JobCreateMinimumRequiredDegree } from './job-create-minimum-required-degree';
import type { JobCreateGrade } from './job-create-grade';

/**
 * Schema for creating a new job
 */
export interface JobCreate {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /** @minLength 10 */
  description: string;
  /** @minLength 1 */
  company_name: string;
  requirements?: string[];
  location?: JobCreateLocation;
  company_highlights?: string[];
  model_provider?: JobCreateModelProvider;
  recruiter_name?: JobCreateRecruiterName;
  language_requirement?: JobCreateLanguageRequirement;
  key_responsibilities?: JobCreateKeyResponsibilities;
  core_skill_requirement?: JobCreateCoreSkillRequirement;
  familiar_with?: JobCreateFamiliarWith;
  work_type?: JobCreateWorkType;
  years_of_experience?: JobCreateYearsOfExperience;
  minimum_required_degree?: JobCreateMinimumRequiredDegree;
  grade?: JobCreateGrade;
}
