/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import type { JobCreateLocation } from './job-create-location';
import type { JobCreateModelProvider } from './job-create-model-provider';

/**
 * Schema for creating a new job
 */
export interface JobCreate {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /** @minLength 10 */
  description: string;
  requirements?: string[];
  location?: JobCreateLocation;
  /** @minLength 1 */
  company_name: string;
  company_highlights?: string[];
  model_provider?: JobCreateModelProvider;
}
