/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response for starting a job
 */
export interface JobStartResponse {
  message: string;
  job_id: string;
  status: string;
}
