/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */

/**
 * Job status enum
 */
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobStatus = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  failed: 'failed',
} as const;
