/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import type { JobLocation } from './job-location';
import type { JobModelProvider } from './job-model-provider';
import type { JobStatus } from './job-status';

/**
 * Schema for job response
 */
export interface Job {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /** @minLength 10 */
  description: string;
  requirements?: string[];
  location?: JobLocation;
  /** @minLength 1 */
  company_name: string;
  company_highlights?: string[];
  model_provider?: JobModelProvider;
  id: string;
  created_at: string;
  status: JobStatus;
}
