/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */

/**
 * Outreach message schema
 */
export interface OutreachMessage {
  id: string;
  candidate_id: string;
  subject: string;
  body: string;
  generated_at: string;
}
