/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  HTTPValidationError,
  Job,
  JobCreate,
  JobStartResponse
} from '.././model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all jobs
 * @summary List Jobs
 */
export const useListJobsApiJobsGetHook = () => {
        const listJobsApiJobsGet = useCustomInstance<Job[]>();

        return useCallback((
    
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return listJobsApiJobsGet(
          {url: `/api/jobs`, method: 'GET', signal
    },
          options);
        }, [listJobsApiJobsGet])
      }
    



export const getListJobsApiJobsGetQueryKey = () => {
    return [
    `/api/jobs`
    ] as const;
    }

    
export const useListJobsApiJobsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJobsApiJobsGetQueryKey();

  const listJobsApiJobsGet =  useListJobsApiJobsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>> = ({ signal }) => listJobsApiJobsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListJobsApiJobsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>>
export type ListJobsApiJobsGetQueryError = unknown


export function useListJobsApiJobsGet<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListJobsApiJobsGet<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListJobsApiJobsGet<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Jobs
 */

export function useListJobsApiJobsGet<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useListJobsApiJobsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useListJobsApiJobsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJobsApiJobsGetQueryKey();

  const listJobsApiJobsGet =  useListJobsApiJobsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>> = ({ signal }) => listJobsApiJobsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListJobsApiJobsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>>
export type ListJobsApiJobsGetSuspenseQueryError = unknown


export function useListJobsApiJobsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListJobsApiJobsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListJobsApiJobsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Jobs
 */

export function useListJobsApiJobsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListJobsApiJobsGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useListJobsApiJobsGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new recruiting job.

Uses content-based duplicate detection: if a job with identical content already exists,
returns the existing job instead of creating a duplicate. This prevents multiple job_ids
for the same logical job regardless of when it was created.
 * @summary Create Job
 */
export const useCreateJobApiJobsPostHook = () => {
        const createJobApiJobsPost = useCustomInstance<Job>();

        return useCallback((
    jobCreate: JobCreate,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return createJobApiJobsPost(
          {url: `/api/jobs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: jobCreate, signal
    },
          options);
        }, [createJobApiJobsPost])
      }
    


export const useCreateJobApiJobsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateJobApiJobsPostHook>>>, TError,{data: JobCreate}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateJobApiJobsPostHook>>>, TError,{data: JobCreate}, TContext> => {

const mutationKey = ['createJobApiJobsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const createJobApiJobsPost =  useCreateJobApiJobsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateJobApiJobsPostHook>>>, {data: JobCreate}> = (props) => {
          const {data} = props ?? {};

          return  createJobApiJobsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateJobApiJobsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateJobApiJobsPostHook>>>>
    export type CreateJobApiJobsPostMutationBody = JobCreate
    export type CreateJobApiJobsPostMutationError = HTTPValidationError

    /**
 * @summary Create Job
 */
export const useCreateJobApiJobsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateJobApiJobsPostHook>>>, TError,{data: JobCreate}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateJobApiJobsPostHook>>>,
        TError,
        {data: JobCreate},
        TContext
      > => {

      const mutationOptions = useCreateJobApiJobsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get job details by ID
 * @summary Get Job
 */
export const useGetJobApiJobsJobIdGetHook = () => {
        const getJobApiJobsJobIdGet = useCustomInstance<Job>();

        return useCallback((
    jobId: string,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return getJobApiJobsJobIdGet(
          {url: `/api/jobs/${jobId}`, method: 'GET', signal
    },
          options);
        }, [getJobApiJobsJobIdGet])
      }
    



export const getGetJobApiJobsJobIdGetQueryKey = (jobId?: string,) => {
    return [
    `/api/jobs/${jobId}`
    ] as const;
    }

    
export const useGetJobApiJobsJobIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobApiJobsJobIdGetQueryKey(jobId);

  const getJobApiJobsJobIdGet =  useGetJobApiJobsJobIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>> = ({ signal }) => getJobApiJobsJobIdGet(jobId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetJobApiJobsJobIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>>
export type GetJobApiJobsJobIdGetQueryError = HTTPValidationError


export function useGetJobApiJobsJobIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetJobApiJobsJobIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetJobApiJobsJobIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Job
 */

export function useGetJobApiJobsJobIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetJobApiJobsJobIdGetQueryOptions(jobId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useGetJobApiJobsJobIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(jobId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobApiJobsJobIdGetQueryKey(jobId);

  const getJobApiJobsJobIdGet =  useGetJobApiJobsJobIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>> = ({ signal }) => getJobApiJobsJobIdGet(jobId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetJobApiJobsJobIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>>
export type GetJobApiJobsJobIdGetSuspenseQueryError = HTTPValidationError


export function useGetJobApiJobsJobIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetJobApiJobsJobIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetJobApiJobsJobIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Job
 */

export function useGetJobApiJobsJobIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetJobApiJobsJobIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetJobApiJobsJobIdGetSuspenseQueryOptions(jobId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Start the agent pipeline for a job
 * @summary Start Job
 */
export const useStartJobApiJobsJobIdStartPostHook = () => {
        const startJobApiJobsJobIdStartPost = useCustomInstance<JobStartResponse>();

        return useCallback((
    jobId: string,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return startJobApiJobsJobIdStartPost(
          {url: `/api/jobs/${jobId}/start`, method: 'POST', signal
    },
          options);
        }, [startJobApiJobsJobIdStartPost])
      }
    


export const useStartJobApiJobsJobIdStartPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useStartJobApiJobsJobIdStartPostHook>>>, TError,{jobId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useStartJobApiJobsJobIdStartPostHook>>>, TError,{jobId: string}, TContext> => {

const mutationKey = ['startJobApiJobsJobIdStartPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const startJobApiJobsJobIdStartPost =  useStartJobApiJobsJobIdStartPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useStartJobApiJobsJobIdStartPostHook>>>, {jobId: string}> = (props) => {
          const {jobId} = props ?? {};

          return  startJobApiJobsJobIdStartPost(jobId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartJobApiJobsJobIdStartPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useStartJobApiJobsJobIdStartPostHook>>>>
    
    export type StartJobApiJobsJobIdStartPostMutationError = HTTPValidationError

    /**
 * @summary Start Job
 */
export const useStartJobApiJobsJobIdStartPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useStartJobApiJobsJobIdStartPostHook>>>, TError,{jobId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useStartJobApiJobsJobIdStartPostHook>>>,
        TError,
        {jobId: string},
        TContext
      > => {

      const mutationOptions = useStartJobApiJobsJobIdStartPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Find more candidates for an existing job.

This endpoint re-runs the agent pipeline but excludes already-found candidates,
uses pagination to get different results, and randomizes search strategies.
 * @summary Find More Candidates
 */
export const useFindMoreCandidatesApiJobsJobIdFindMorePostHook = () => {
        const findMoreCandidatesApiJobsJobIdFindMorePost = useCustomInstance<JobStartResponse>();

        return useCallback((
    jobId: string,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return findMoreCandidatesApiJobsJobIdFindMorePost(
          {url: `/api/jobs/${jobId}/find-more`, method: 'POST', signal
    },
          options);
        }, [findMoreCandidatesApiJobsJobIdFindMorePost])
      }
    


export const useFindMoreCandidatesApiJobsJobIdFindMorePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useFindMoreCandidatesApiJobsJobIdFindMorePostHook>>>, TError,{jobId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useFindMoreCandidatesApiJobsJobIdFindMorePostHook>>>, TError,{jobId: string}, TContext> => {

const mutationKey = ['findMoreCandidatesApiJobsJobIdFindMorePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const findMoreCandidatesApiJobsJobIdFindMorePost =  useFindMoreCandidatesApiJobsJobIdFindMorePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useFindMoreCandidatesApiJobsJobIdFindMorePostHook>>>, {jobId: string}> = (props) => {
          const {jobId} = props ?? {};

          return  findMoreCandidatesApiJobsJobIdFindMorePost(jobId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FindMoreCandidatesApiJobsJobIdFindMorePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useFindMoreCandidatesApiJobsJobIdFindMorePostHook>>>>
    
    export type FindMoreCandidatesApiJobsJobIdFindMorePostMutationError = HTTPValidationError

    /**
 * @summary Find More Candidates
 */
export const useFindMoreCandidatesApiJobsJobIdFindMorePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useFindMoreCandidatesApiJobsJobIdFindMorePostHook>>>, TError,{jobId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useFindMoreCandidatesApiJobsJobIdFindMorePostHook>>>,
        TError,
        {jobId: string},
        TContext
      > => {

      const mutationOptions = useFindMoreCandidatesApiJobsJobIdFindMorePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    