export { default } from '@/components/dashboard/dashboard'
export { default as Dashboard } from '@/components/dashboard/dashboard'
export { default as AgentStatus } from '@/components/dashboard/agent-status'
export { default as AgentSwarm } from '@/components/dashboard/agent-swarm'
export { default as AgentCharacter } from '@/components/dashboard/agent-character'
export { default as CandidateCard } from '@/components/dashboard/candidate-card'
export { default as MetricsPanel } from '@/components/dashboard/metrics-panel'
