/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  GetVectorCandidatesApiVectorCandidatesGetParams,
  HTTPValidationError
} from '.././model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get all candidates for a job from Weaviate vector database.

Args:
    job_id: Job ID to filter by (required)
    min_fit_score: Minimum fit score threshold (optional)

Returns:
    List of candidates from vector database
 * @summary Get Vector Candidates
 */
export const useGetVectorCandidatesApiVectorCandidatesGetHook = () => {
        const getVectorCandidatesApiVectorCandidatesGet = useCustomInstance<unknown>();

        return useCallback((
    params: GetVectorCandidatesApiVectorCandidatesGetParams,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return getVectorCandidatesApiVectorCandidatesGet(
          {url: `/api/vector/candidates`, method: 'GET',
        params, signal
    },
          options);
        }, [getVectorCandidatesApiVectorCandidatesGet])
      }
    



export const getGetVectorCandidatesApiVectorCandidatesGetQueryKey = (params?: GetVectorCandidatesApiVectorCandidatesGetParams,) => {
    return [
    `/api/vector/candidates`, ...(params ? [params] : [])
    ] as const;
    }

    
export const useGetVectorCandidatesApiVectorCandidatesGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVectorCandidatesApiVectorCandidatesGetQueryKey(params);

  const getVectorCandidatesApiVectorCandidatesGet =  useGetVectorCandidatesApiVectorCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>> = ({ signal }) => getVectorCandidatesApiVectorCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVectorCandidatesApiVectorCandidatesGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>>
export type GetVectorCandidatesApiVectorCandidatesGetQueryError = HTTPValidationError


export function useGetVectorCandidatesApiVectorCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVectorCandidatesApiVectorCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVectorCandidatesApiVectorCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Vector Candidates
 */

export function useGetVectorCandidatesApiVectorCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetVectorCandidatesApiVectorCandidatesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useGetVectorCandidatesApiVectorCandidatesGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVectorCandidatesApiVectorCandidatesGetQueryKey(params);

  const getVectorCandidatesApiVectorCandidatesGet =  useGetVectorCandidatesApiVectorCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>> = ({ signal }) => getVectorCandidatesApiVectorCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVectorCandidatesApiVectorCandidatesGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>>
export type GetVectorCandidatesApiVectorCandidatesGetSuspenseQueryError = HTTPValidationError


export function useGetVectorCandidatesApiVectorCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVectorCandidatesApiVectorCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVectorCandidatesApiVectorCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Vector Candidates
 */

export function useGetVectorCandidatesApiVectorCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: GetVectorCandidatesApiVectorCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetVectorCandidatesApiVectorCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetVectorCandidatesApiVectorCandidatesGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




