/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Search candidates using semantic similarity across ALL jobs.

This endpoint searches the entire candidate pool globally, not filtered by job.
A candidate who applied for one position might be perfect for another based on
their strengths and skills.

Args:
    query: Natural language query describing desired candidate strengths (min 3 chars)
    limit: Maximum number of results (default 10, max 100)

Returns:
    List of candidates ranked by similarity across all jobs
 * @summary Search Candidates By Strengths
 */
export const searchCandidatesByStrengthsApiSearchCandidatesGetQueryLimitDefault = 10;

export const searchCandidatesByStrengthsApiSearchCandidatesGetQueryParams = zod.object({
  "query": zod.string(),
  "limit": zod.number().default(searchCandidatesByStrengthsApiSearchCandidatesGetQueryLimitDefault)
})

export const searchCandidatesByStrengthsApiSearchCandidatesGetResponse = zod.unknown()

