/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  HTTPValidationError,
  SearchCandidatesByStrengthsApiSearchCandidatesGetParams
} from '.././model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Search candidates using semantic similarity across ALL jobs.

This endpoint searches the entire candidate pool globally, not filtered by job.
A candidate who applied for one position might be perfect for another based on
their strengths and skills.

Args:
    query: Natural language query describing desired candidate strengths (min 3 chars)
    limit: Maximum number of results (default 10, max 100)

Returns:
    List of candidates ranked by similarity across all jobs
 * @summary Search Candidates By Strengths
 */
export const useSearchCandidatesByStrengthsApiSearchCandidatesGetHook = () => {
        const searchCandidatesByStrengthsApiSearchCandidatesGet = useCustomInstance<unknown>();

        return useCallback((
    params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return searchCandidatesByStrengthsApiSearchCandidatesGet(
          {url: `/api/search/candidates`, method: 'GET',
        params, signal
    },
          options);
        }, [searchCandidatesByStrengthsApiSearchCandidatesGet])
      }
    



export const getSearchCandidatesByStrengthsApiSearchCandidatesGetQueryKey = (params?: SearchCandidatesByStrengthsApiSearchCandidatesGetParams,) => {
    return [
    `/api/search/candidates`, ...(params ? [params] : [])
    ] as const;
    }

    
export const useSearchCandidatesByStrengthsApiSearchCandidatesGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchCandidatesByStrengthsApiSearchCandidatesGetQueryKey(params);

  const searchCandidatesByStrengthsApiSearchCandidatesGet =  useSearchCandidatesByStrengthsApiSearchCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>> = ({ signal }) => searchCandidatesByStrengthsApiSearchCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SearchCandidatesByStrengthsApiSearchCandidatesGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>>
export type SearchCandidatesByStrengthsApiSearchCandidatesGetQueryError = HTTPValidationError


export function useSearchCandidatesByStrengthsApiSearchCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchCandidatesByStrengthsApiSearchCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchCandidatesByStrengthsApiSearchCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Search Candidates By Strengths
 */

export function useSearchCandidatesByStrengthsApiSearchCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useSearchCandidatesByStrengthsApiSearchCandidatesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useSearchCandidatesByStrengthsApiSearchCandidatesGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchCandidatesByStrengthsApiSearchCandidatesGetQueryKey(params);

  const searchCandidatesByStrengthsApiSearchCandidatesGet =  useSearchCandidatesByStrengthsApiSearchCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>> = ({ signal }) => searchCandidatesByStrengthsApiSearchCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SearchCandidatesByStrengthsApiSearchCandidatesGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>>
export type SearchCandidatesByStrengthsApiSearchCandidatesGetSuspenseQueryError = HTTPValidationError


export function useSearchCandidatesByStrengthsApiSearchCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchCandidatesByStrengthsApiSearchCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchCandidatesByStrengthsApiSearchCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Search Candidates By Strengths
 */

export function useSearchCandidatesByStrengthsApiSearchCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: SearchCandidatesByStrengthsApiSearchCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchCandidatesByStrengthsApiSearchCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useSearchCandidatesByStrengthsApiSearchCandidatesGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




