/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * List candidates, optionally filtered by job_id
 * @summary List Candidates
 */
export const listCandidatesApiCandidatesGetQueryParams = zod.object({
  "job_id": zod.string().optional()
})

export const listCandidatesApiCandidatesGetResponseAnalysisOneFitScoreMin = 0;
export const listCandidatesApiCandidatesGetResponseAnalysisOneFitScoreMax = 100;



export const listCandidatesApiCandidatesGetResponseItem = zod.object({
  "username": zod.string(),
  "profile_url": zod.string(),
  "avatar_url": zod.union([zod.string(),zod.null()]).optional(),
  "bio": zod.union([zod.string(),zod.null()]).optional(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.string(),
  "job_id": zod.string(),
  "created_at": zod.iso.datetime({}),
  "analysis": zod.union([zod.object({
  "fit_score": zod.number().min(listCandidatesApiCandidatesGetResponseAnalysisOneFitScoreMin).max(listCandidatesApiCandidatesGetResponseAnalysisOneFitScoreMax),
  "skills": zod.array(zod.string()).optional(),
  "strengths": zod.array(zod.string()).optional(),
  "concerns": zod.array(zod.string()).optional(),
  "top_repositories": zod.array(zod.object({

})).optional()
}).describe('Candidate analysis results'),zod.null()]).optional()
}).describe('Full candidate schema')
export const listCandidatesApiCandidatesGetResponse = zod.array(listCandidatesApiCandidatesGetResponseItem)

/**
 * Get candidate details
 * @summary Get Candidate
 */
export const getCandidateApiCandidatesCandidateIdGetParams = zod.object({
  "candidate_id": zod.string()
})

export const getCandidateApiCandidatesCandidateIdGetResponseAnalysisOneFitScoreMin = 0;
export const getCandidateApiCandidatesCandidateIdGetResponseAnalysisOneFitScoreMax = 100;



export const getCandidateApiCandidatesCandidateIdGetResponse = zod.object({
  "username": zod.string(),
  "profile_url": zod.string(),
  "avatar_url": zod.union([zod.string(),zod.null()]).optional(),
  "bio": zod.union([zod.string(),zod.null()]).optional(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.string(),
  "job_id": zod.string(),
  "created_at": zod.iso.datetime({}),
  "analysis": zod.union([zod.object({
  "fit_score": zod.number().min(getCandidateApiCandidatesCandidateIdGetResponseAnalysisOneFitScoreMin).max(getCandidateApiCandidatesCandidateIdGetResponseAnalysisOneFitScoreMax),
  "skills": zod.array(zod.string()).optional(),
  "strengths": zod.array(zod.string()).optional(),
  "concerns": zod.array(zod.string()).optional(),
  "top_repositories": zod.array(zod.object({

})).optional()
}).describe('Candidate analysis results'),zod.null()]).optional()
}).describe('Full candidate schema')

/**
 * Get outreach message for a candidate
 * @summary Get Candidate Message
 */
export const getCandidateMessageApiCandidatesCandidateIdMessageGetParams = zod.object({
  "candidate_id": zod.string()
})

export const getCandidateMessageApiCandidatesCandidateIdMessageGetResponse = zod.object({
  "id": zod.string(),
  "candidate_id": zod.string(),
  "subject": zod.string(),
  "body": zod.string(),
  "generated_at": zod.iso.datetime({})
}).describe('Outreach message schema')

