/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import { useCustomInstance } from '../../../hooks/use-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Health check endpoint
 * @summary Health Check
 */
export const useHealthCheckHealthGetHook = () => {
        const healthCheckHealthGet = useCustomInstance<unknown>();

        return useCallback((
    
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return healthCheckHealthGet(
          {url: `/health`, method: 'GET', signal
    },
          options);
        }, [healthCheckHealthGet])
      }
    



export const getHealthCheckHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const useHealthCheckHealthGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();

  const healthCheckHealthGet =  useHealthCheckHealthGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>> = ({ signal }) => healthCheckHealthGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type HealthCheckHealthGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>
export type HealthCheckHealthGetQueryError = unknown


export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useHealthCheckHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useHealthCheckHealthGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();

  const healthCheckHealthGet =  useHealthCheckHealthGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>> = ({ signal }) => healthCheckHealthGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type HealthCheckHealthGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>
export type HealthCheckHealthGetSuspenseQueryError = unknown


export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useHealthCheckHealthGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




