/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * List all jobs
 * @summary List Jobs
 */
export const listJobsApiJobsGetResponseTitleMax = 200;

export const listJobsApiJobsGetResponseDescriptionMin = 10;


export const listJobsApiJobsGetResponseModelProviderOneRegExp = new RegExp('^(claude|gemini)$');


export const listJobsApiJobsGetResponseItem = zod.object({
  "title": zod.string().min(1).max(listJobsApiJobsGetResponseTitleMax),
  "description": zod.string().min(listJobsApiJobsGetResponseDescriptionMin),
  "company_name": zod.string().min(1),
  "requirements": zod.array(zod.string()).optional(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "company_highlights": zod.array(zod.string()).optional(),
  "model_provider": zod.union([zod.string().regex(listJobsApiJobsGetResponseModelProviderOneRegExp),zod.null()]).optional(),
  "recruiter_name": zod.union([zod.string(),zod.null()]).optional(),
  "language_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "key_responsibilities": zod.union([zod.string(),zod.null()]).optional(),
  "core_skill_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "familiar_with": zod.union([zod.string(),zod.null()]).optional(),
  "work_type": zod.union([zod.string(),zod.null()]).optional(),
  "years_of_experience": zod.union([zod.number(),zod.null()]).optional(),
  "minimum_required_degree": zod.union([zod.string(),zod.null()]).optional(),
  "grade": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.string(),
  "created_at": zod.iso.datetime({}),
  "status": zod.enum(['pending', 'running', 'completed', 'failed']).describe('Job status enum')
}).describe('Schema for job response')
export const listJobsApiJobsGetResponse = zod.array(listJobsApiJobsGetResponseItem)

/**
 * Create a new recruiting job.

Uses content-based duplicate detection: if a job with identical content already exists,
returns the existing job instead of creating a duplicate. This prevents multiple job_ids
for the same logical job regardless of when it was created.
 * @summary Create Job
 */
export const createJobApiJobsPostBodyTitleMax = 200;

export const createJobApiJobsPostBodyDescriptionMin = 10;


export const createJobApiJobsPostBodyModelProviderOneRegExp = new RegExp('^(claude|gemini)$');


export const createJobApiJobsPostBody = zod.object({
  "title": zod.string().min(1).max(createJobApiJobsPostBodyTitleMax),
  "description": zod.string().min(createJobApiJobsPostBodyDescriptionMin),
  "company_name": zod.string().min(1),
  "requirements": zod.array(zod.string()).optional(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "company_highlights": zod.array(zod.string()).optional(),
  "model_provider": zod.union([zod.string().regex(createJobApiJobsPostBodyModelProviderOneRegExp),zod.null()]).optional(),
  "recruiter_name": zod.union([zod.string(),zod.null()]).optional(),
  "language_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "key_responsibilities": zod.union([zod.string(),zod.null()]).optional(),
  "core_skill_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "familiar_with": zod.union([zod.string(),zod.null()]).optional(),
  "work_type": zod.union([zod.string(),zod.null()]).optional(),
  "years_of_experience": zod.union([zod.number(),zod.null()]).optional(),
  "minimum_required_degree": zod.union([zod.string(),zod.null()]).optional(),
  "grade": zod.union([zod.number(),zod.null()]).optional()
}).describe('Schema for creating a new job')

export const createJobApiJobsPostResponseTitleMax = 200;

export const createJobApiJobsPostResponseDescriptionMin = 10;


export const createJobApiJobsPostResponseModelProviderOneRegExp = new RegExp('^(claude|gemini)$');


export const createJobApiJobsPostResponse = zod.object({
  "title": zod.string().min(1).max(createJobApiJobsPostResponseTitleMax),
  "description": zod.string().min(createJobApiJobsPostResponseDescriptionMin),
  "company_name": zod.string().min(1),
  "requirements": zod.array(zod.string()).optional(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "company_highlights": zod.array(zod.string()).optional(),
  "model_provider": zod.union([zod.string().regex(createJobApiJobsPostResponseModelProviderOneRegExp),zod.null()]).optional(),
  "recruiter_name": zod.union([zod.string(),zod.null()]).optional(),
  "language_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "key_responsibilities": zod.union([zod.string(),zod.null()]).optional(),
  "core_skill_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "familiar_with": zod.union([zod.string(),zod.null()]).optional(),
  "work_type": zod.union([zod.string(),zod.null()]).optional(),
  "years_of_experience": zod.union([zod.number(),zod.null()]).optional(),
  "minimum_required_degree": zod.union([zod.string(),zod.null()]).optional(),
  "grade": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.string(),
  "created_at": zod.iso.datetime({}),
  "status": zod.enum(['pending', 'running', 'completed', 'failed']).describe('Job status enum')
}).describe('Schema for job response')

/**
 * Get job details by ID
 * @summary Get Job
 */
export const getJobApiJobsJobIdGetParams = zod.object({
  "job_id": zod.string()
})

export const getJobApiJobsJobIdGetResponseTitleMax = 200;

export const getJobApiJobsJobIdGetResponseDescriptionMin = 10;


export const getJobApiJobsJobIdGetResponseModelProviderOneRegExp = new RegExp('^(claude|gemini)$');


export const getJobApiJobsJobIdGetResponse = zod.object({
  "title": zod.string().min(1).max(getJobApiJobsJobIdGetResponseTitleMax),
  "description": zod.string().min(getJobApiJobsJobIdGetResponseDescriptionMin),
  "company_name": zod.string().min(1),
  "requirements": zod.array(zod.string()).optional(),
  "location": zod.union([zod.string(),zod.null()]).optional(),
  "company_highlights": zod.array(zod.string()).optional(),
  "model_provider": zod.union([zod.string().regex(getJobApiJobsJobIdGetResponseModelProviderOneRegExp),zod.null()]).optional(),
  "recruiter_name": zod.union([zod.string(),zod.null()]).optional(),
  "language_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "key_responsibilities": zod.union([zod.string(),zod.null()]).optional(),
  "core_skill_requirement": zod.union([zod.string(),zod.null()]).optional(),
  "familiar_with": zod.union([zod.string(),zod.null()]).optional(),
  "work_type": zod.union([zod.string(),zod.null()]).optional(),
  "years_of_experience": zod.union([zod.number(),zod.null()]).optional(),
  "minimum_required_degree": zod.union([zod.string(),zod.null()]).optional(),
  "grade": zod.union([zod.number(),zod.null()]).optional(),
  "id": zod.string(),
  "created_at": zod.iso.datetime({}),
  "status": zod.enum(['pending', 'running', 'completed', 'failed']).describe('Job status enum')
}).describe('Schema for job response')

/**
 * Start the agent pipeline for a job
 * @summary Start Job
 */
export const startJobApiJobsJobIdStartPostParams = zod.object({
  "job_id": zod.string()
})

export const startJobApiJobsJobIdStartPostResponse = zod.object({
  "message": zod.string(),
  "job_id": zod.string(),
  "status": zod.string()
}).describe('Response for starting a job')

/**
 * Find more candidates for an existing job.

This endpoint re-runs the agent pipeline but excludes already-found candidates,
uses pagination to get different results, and randomizes search strategies.
 * @summary Find More Candidates
 */
export const findMoreCandidatesApiJobsJobIdFindMorePostParams = zod.object({
  "job_id": zod.string()
})

export const findMoreCandidatesApiJobsJobIdFindMorePostResponse = zod.object({
  "message": zod.string(),
  "job_id": zod.string(),
  "status": zod.string()
}).describe('Response for starting a job')

