/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  ForceGraphData,
  GetAllCandidatesGraphApiNeo4jCandidatesGetParams,
  GetGraphByFilterApiNeo4jGraphFilterGetParams,
  HTTPValidationError
} from '.././model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get a snapshot of the candidate graph.
Returns nodes and links formatted for react-force-graph-2d.
 * @summary Get All Candidates Graph
 */
export const useGetAllCandidatesGraphApiNeo4jCandidatesGetHook = () => {
        const getAllCandidatesGraphApiNeo4jCandidatesGet = useCustomInstance<ForceGraphData>();

        return useCallback((
    params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return getAllCandidatesGraphApiNeo4jCandidatesGet(
          {url: `/api/neo4j/candidates`, method: 'GET',
        params, signal
    },
          options);
        }, [getAllCandidatesGraphApiNeo4jCandidatesGet])
      }
    



export const getGetAllCandidatesGraphApiNeo4jCandidatesGetQueryKey = (params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams,) => {
    return [
    `/api/neo4j/candidates`, ...(params ? [params] : [])
    ] as const;
    }

    
export const useGetAllCandidatesGraphApiNeo4jCandidatesGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCandidatesGraphApiNeo4jCandidatesGetQueryKey(params);

  const getAllCandidatesGraphApiNeo4jCandidatesGet =  useGetAllCandidatesGraphApiNeo4jCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>> = ({ signal }) => getAllCandidatesGraphApiNeo4jCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllCandidatesGraphApiNeo4jCandidatesGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>>
export type GetAllCandidatesGraphApiNeo4jCandidatesGetQueryError = HTTPValidationError


export function useGetAllCandidatesGraphApiNeo4jCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllCandidatesGraphApiNeo4jCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllCandidatesGraphApiNeo4jCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get All Candidates Graph
 */

export function useGetAllCandidatesGraphApiNeo4jCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetAllCandidatesGraphApiNeo4jCandidatesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useGetAllCandidatesGraphApiNeo4jCandidatesGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCandidatesGraphApiNeo4jCandidatesGetQueryKey(params);

  const getAllCandidatesGraphApiNeo4jCandidatesGet =  useGetAllCandidatesGraphApiNeo4jCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>> = ({ signal }) => getAllCandidatesGraphApiNeo4jCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllCandidatesGraphApiNeo4jCandidatesGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>>
export type GetAllCandidatesGraphApiNeo4jCandidatesGetSuspenseQueryError = HTTPValidationError


export function useGetAllCandidatesGraphApiNeo4jCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllCandidatesGraphApiNeo4jCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllCandidatesGraphApiNeo4jCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get All Candidates Graph
 */

export function useGetAllCandidatesGraphApiNeo4jCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: GetAllCandidatesGraphApiNeo4jCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllCandidatesGraphApiNeo4jCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetAllCandidatesGraphApiNeo4jCandidatesGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get the graph for a specific candidate by username or ID.
Returns nodes and links formatted for react-force-graph-2d.
 * @summary Get Candidate Graph
 */
export const useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook = () => {
        const getCandidateGraphApiNeo4jCandidatesUsernameOrIdGet = useCustomInstance<ForceGraphData>();

        return useCallback((
    usernameOrId: string,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return getCandidateGraphApiNeo4jCandidatesUsernameOrIdGet(
          {url: `/api/neo4j/candidates/${usernameOrId}`, method: 'GET', signal
    },
          options);
        }, [getCandidateGraphApiNeo4jCandidatesUsernameOrIdGet])
      }
    



export const getGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetQueryKey = (usernameOrId?: string,) => {
    return [
    `/api/neo4j/candidates/${usernameOrId}`
    ] as const;
    }

    
export const useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(usernameOrId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetQueryKey(usernameOrId);

  const getCandidateGraphApiNeo4jCandidatesUsernameOrIdGet =  useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>> = ({ signal }) => getCandidateGraphApiNeo4jCandidatesUsernameOrIdGet(usernameOrId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(usernameOrId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>>
export type GetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetQueryError = HTTPValidationError


export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Candidate Graph
 */

export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetQueryOptions(usernameOrId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(usernameOrId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetQueryKey(usernameOrId);

  const getCandidateGraphApiNeo4jCandidatesUsernameOrIdGet =  useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>> = ({ signal }) => getCandidateGraphApiNeo4jCandidatesUsernameOrIdGet(usernameOrId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>>
export type GetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspenseQueryError = HTTPValidationError


export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Candidate Graph
 */

export function useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError = HTTPValidationError>(
 usernameOrId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetCandidateGraphApiNeo4jCandidatesUsernameOrIdGetSuspenseQueryOptions(usernameOrId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Delete a candidate node and its relationships.
 * @summary Delete Candidate
 */
export const useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook = () => {
        const deleteCandidateApiNeo4jCandidatesCandidateIdDelete = useCustomInstance<unknown>();

        return useCallback((
    candidateId: string,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,) => {
        return deleteCandidateApiNeo4jCandidatesCandidateIdDelete(
          {url: `/api/neo4j/candidates/${candidateId}`, method: 'DELETE'
    },
          options);
        }, [deleteCandidateApiNeo4jCandidatesCandidateIdDelete])
      }
    


export const useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook>>>, TError,{candidateId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook>>>, TError,{candidateId: string}, TContext> => {

const mutationKey = ['deleteCandidateApiNeo4jCandidatesCandidateIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const deleteCandidateApiNeo4jCandidatesCandidateIdDelete =  useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook>>>, {candidateId: string}> = (props) => {
          const {candidateId} = props ?? {};

          return  deleteCandidateApiNeo4jCandidatesCandidateIdDelete(candidateId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCandidateApiNeo4jCandidatesCandidateIdDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook>>>>
    
    export type DeleteCandidateApiNeo4jCandidatesCandidateIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Candidate
 */
export const useDeleteCandidateApiNeo4jCandidatesCandidateIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook>>>, TError,{candidateId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteHook>>>,
        TError,
        {candidateId: string},
        TContext
      > => {

      const mutationOptions = useDeleteCandidateApiNeo4jCandidatesCandidateIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get graph centered around a specific entity (Skill, Location, etc.).
Returns nodes and links formatted for react-force-graph-2d.
 * @summary Get Graph By Filter
 */
export const useGetGraphByFilterApiNeo4jGraphFilterGetHook = () => {
        const getGraphByFilterApiNeo4jGraphFilterGet = useCustomInstance<ForceGraphData>();

        return useCallback((
    params: GetGraphByFilterApiNeo4jGraphFilterGetParams,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return getGraphByFilterApiNeo4jGraphFilterGet(
          {url: `/api/neo4j/graph/filter`, method: 'GET',
        params, signal
    },
          options);
        }, [getGraphByFilterApiNeo4jGraphFilterGet])
      }
    



export const getGetGraphByFilterApiNeo4jGraphFilterGetQueryKey = (params?: GetGraphByFilterApiNeo4jGraphFilterGetParams,) => {
    return [
    `/api/neo4j/graph/filter`, ...(params ? [params] : [])
    ] as const;
    }

    
export const useGetGraphByFilterApiNeo4jGraphFilterGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGraphByFilterApiNeo4jGraphFilterGetQueryKey(params);

  const getGraphByFilterApiNeo4jGraphFilterGet =  useGetGraphByFilterApiNeo4jGraphFilterGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>> = ({ signal }) => getGraphByFilterApiNeo4jGraphFilterGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetGraphByFilterApiNeo4jGraphFilterGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>>
export type GetGraphByFilterApiNeo4jGraphFilterGetQueryError = HTTPValidationError


export function useGetGraphByFilterApiNeo4jGraphFilterGet<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetGraphByFilterApiNeo4jGraphFilterGet<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetGraphByFilterApiNeo4jGraphFilterGet<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Graph By Filter
 */

export function useGetGraphByFilterApiNeo4jGraphFilterGet<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetGraphByFilterApiNeo4jGraphFilterGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useGetGraphByFilterApiNeo4jGraphFilterGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGraphByFilterApiNeo4jGraphFilterGetQueryKey(params);

  const getGraphByFilterApiNeo4jGraphFilterGet =  useGetGraphByFilterApiNeo4jGraphFilterGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>> = ({ signal }) => getGraphByFilterApiNeo4jGraphFilterGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetGraphByFilterApiNeo4jGraphFilterGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>>
export type GetGraphByFilterApiNeo4jGraphFilterGetSuspenseQueryError = HTTPValidationError


export function useGetGraphByFilterApiNeo4jGraphFilterGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetGraphByFilterApiNeo4jGraphFilterGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetGraphByFilterApiNeo4jGraphFilterGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Graph By Filter
 */

export function useGetGraphByFilterApiNeo4jGraphFilterGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError = HTTPValidationError>(
 params: GetGraphByFilterApiNeo4jGraphFilterGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetGraphByFilterApiNeo4jGraphFilterGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetGraphByFilterApiNeo4jGraphFilterGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




