/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Get all candidates for a job from Weaviate vector database.

Args:
    job_id: Job ID to filter by (required)
    min_fit_score: Minimum fit score threshold (optional)

Returns:
    List of candidates from vector database
 * @summary Get Vector Candidates
 */
export const getVectorCandidatesApiVectorCandidatesGetQueryParams = zod.object({
  "job_id": zod.string(),
  "min_fit_score": zod.number().optional()
})

export const getVectorCandidatesApiVectorCandidatesGetResponse = zod.unknown()

