/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * Autonomous Recruiting Agent Swarm
 * AI-powered multi-agent system for recruiting
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  Candidate,
  HTTPValidationError,
  ListCandidatesApiCandidatesGetParams,
  OutreachMessage
} from '.././model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List candidates, optionally filtered by job_id
 * @summary List Candidates
 */
export const useListCandidatesApiCandidatesGetHook = () => {
        const listCandidatesApiCandidatesGet = useCustomInstance<Candidate[]>();

        return useCallback((
    params?: ListCandidatesApiCandidatesGetParams,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return listCandidatesApiCandidatesGet(
          {url: `/api/candidates`, method: 'GET',
        params, signal
    },
          options);
        }, [listCandidatesApiCandidatesGet])
      }
    



export const getListCandidatesApiCandidatesGetQueryKey = (params?: ListCandidatesApiCandidatesGetParams,) => {
    return [
    `/api/candidates`, ...(params ? [params] : [])
    ] as const;
    }

    
export const useListCandidatesApiCandidatesGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCandidatesApiCandidatesGetQueryKey(params);

  const listCandidatesApiCandidatesGet =  useListCandidatesApiCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>> = ({ signal }) => listCandidatesApiCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListCandidatesApiCandidatesGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>>
export type ListCandidatesApiCandidatesGetQueryError = HTTPValidationError


export function useListCandidatesApiCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  ListCandidatesApiCandidatesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCandidatesApiCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCandidatesApiCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Candidates
 */

export function useListCandidatesApiCandidatesGet<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useListCandidatesApiCandidatesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useListCandidatesApiCandidatesGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCandidatesApiCandidatesGetQueryKey(params);

  const listCandidatesApiCandidatesGet =  useListCandidatesApiCandidatesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>> = ({ signal }) => listCandidatesApiCandidatesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListCandidatesApiCandidatesGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>>
export type ListCandidatesApiCandidatesGetSuspenseQueryError = HTTPValidationError


export function useListCandidatesApiCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  ListCandidatesApiCandidatesGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCandidatesApiCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCandidatesApiCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Candidates
 */

export function useListCandidatesApiCandidatesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError = HTTPValidationError>(
 params?: ListCandidatesApiCandidatesGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCandidatesApiCandidatesGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useListCandidatesApiCandidatesGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get candidate details
 * @summary Get Candidate
 */
export const useGetCandidateApiCandidatesCandidateIdGetHook = () => {
        const getCandidateApiCandidatesCandidateIdGet = useCustomInstance<Candidate>();

        return useCallback((
    candidateId: string,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return getCandidateApiCandidatesCandidateIdGet(
          {url: `/api/candidates/${candidateId}`, method: 'GET', signal
    },
          options);
        }, [getCandidateApiCandidatesCandidateIdGet])
      }
    



export const getGetCandidateApiCandidatesCandidateIdGetQueryKey = (candidateId?: string,) => {
    return [
    `/api/candidates/${candidateId}`
    ] as const;
    }

    
export const useGetCandidateApiCandidatesCandidateIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateApiCandidatesCandidateIdGetQueryKey(candidateId);

  const getCandidateApiCandidatesCandidateIdGet =  useGetCandidateApiCandidatesCandidateIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>> = ({ signal }) => getCandidateApiCandidatesCandidateIdGet(candidateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(candidateId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCandidateApiCandidatesCandidateIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>>
export type GetCandidateApiCandidatesCandidateIdGetQueryError = HTTPValidationError


export function useGetCandidateApiCandidatesCandidateIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateApiCandidatesCandidateIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateApiCandidatesCandidateIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Candidate
 */

export function useGetCandidateApiCandidatesCandidateIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetCandidateApiCandidatesCandidateIdGetQueryOptions(candidateId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useGetCandidateApiCandidatesCandidateIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateApiCandidatesCandidateIdGetQueryKey(candidateId);

  const getCandidateApiCandidatesCandidateIdGet =  useGetCandidateApiCandidatesCandidateIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>> = ({ signal }) => getCandidateApiCandidatesCandidateIdGet(candidateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCandidateApiCandidatesCandidateIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>>
export type GetCandidateApiCandidatesCandidateIdGetSuspenseQueryError = HTTPValidationError


export function useGetCandidateApiCandidatesCandidateIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateApiCandidatesCandidateIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateApiCandidatesCandidateIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Candidate
 */

export function useGetCandidateApiCandidatesCandidateIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateApiCandidatesCandidateIdGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetCandidateApiCandidatesCandidateIdGetSuspenseQueryOptions(candidateId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get outreach message for a candidate
 * @summary Get Candidate Message
 */
export const useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook = () => {
        const getCandidateMessageApiCandidatesCandidateIdMessageGet = useCustomInstance<OutreachMessage>();

        return useCallback((
    candidateId: string,
 options?: SecondParameter<ReturnType<typeof useCustomInstance>>,signal?: AbortSignal
) => {
        return getCandidateMessageApiCandidatesCandidateIdMessageGet(
          {url: `/api/candidates/${candidateId}/message`, method: 'GET', signal
    },
          options);
        }, [getCandidateMessageApiCandidatesCandidateIdMessageGet])
      }
    



export const getGetCandidateMessageApiCandidatesCandidateIdMessageGetQueryKey = (candidateId?: string,) => {
    return [
    `/api/candidates/${candidateId}/message`
    ] as const;
    }

    
export const useGetCandidateMessageApiCandidatesCandidateIdMessageGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateMessageApiCandidatesCandidateIdMessageGetQueryKey(candidateId);

  const getCandidateMessageApiCandidatesCandidateIdMessageGet =  useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>> = ({ signal }) => getCandidateMessageApiCandidatesCandidateIdMessageGet(candidateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(candidateId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCandidateMessageApiCandidatesCandidateIdMessageGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>>
export type GetCandidateMessageApiCandidatesCandidateIdMessageGetQueryError = HTTPValidationError


export function useGetCandidateMessageApiCandidatesCandidateIdMessageGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateMessageApiCandidatesCandidateIdMessageGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>
        > , 'initialData'
      >, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateMessageApiCandidatesCandidateIdMessageGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Candidate Message
 */

export function useGetCandidateMessageApiCandidatesCandidateIdMessageGet<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetCandidateMessageApiCandidatesCandidateIdMessageGetQueryOptions(candidateId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const useGetCandidateMessageApiCandidatesCandidateIdMessageGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateMessageApiCandidatesCandidateIdMessageGetQueryKey(candidateId);

  const getCandidateMessageApiCandidatesCandidateIdMessageGet =  useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>> = ({ signal }) => getCandidateMessageApiCandidatesCandidateIdMessageGet(candidateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCandidateMessageApiCandidatesCandidateIdMessageGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>>
export type GetCandidateMessageApiCandidatesCandidateIdMessageGetSuspenseQueryError = HTTPValidationError


export function useGetCandidateMessageApiCandidatesCandidateIdMessageGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateMessageApiCandidatesCandidateIdMessageGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCandidateMessageApiCandidatesCandidateIdMessageGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Candidate Message
 */

export function useGetCandidateMessageApiCandidatesCandidateIdMessageGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError = HTTPValidationError>(
 candidateId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCandidateMessageApiCandidatesCandidateIdMessageGetHook>>>, TError, TData>>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = useGetCandidateMessageApiCandidatesCandidateIdMessageGetSuspenseQueryOptions(candidateId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




